import logging
from typing import List, Dict, Any
from app.llm.gemini import query_gemini_json

logger = logging.getLogger(__name__)

async def run_layer2_ai_adversarial_review(
    hypothesis_label: str,
    sequence: List[Dict[str, Any]],
    layer1_issues: List[Dict[str, Any]],
    gaps: List[Dict[str, Any]]
) -> List[Dict[str, Any]]:
    """
    AI Adversarial Review (Layer 2).
    Uses Live Google Gemini AI to critically challenge reconstructive theft sequences,
    flagging blind spots, camera occlusion, perceptual drift, and reasonable doubt.
    """
    # Deterministic baseline fallback
    fallback_notes: List[Dict[str, Any]] = [
        {
            "dimension": "BLIND_SPOT_CONCEALMENT_AMBIGUITY",
            "severity": "HIGH",
            "observation_counterpoint": "Camera angle at aisle 3 captures proximity to display shelf, but blind spot between aisle and exit prevents visual confirmation of item inside the backpack.",
            "alternative_explanation": "Item could have been transferred to an accomplice or hidden in an unmonitored display rack prior to exiting.",
            "investigative_action": "Inspect store bins, secondary shelves, and request external corridor CCTV from adjoining tenant."
        },
        {
            "dimension": "CAMERA_ANGLE_AND_OCCLUSION",
            "severity": "MEDIUM",
            "observation_counterpoint": "Subject's back is partially turned to Camera CCTV-02 during the 18-second loitering interval at the electronics shelf.",
            "alternative_explanation": "Subject's motion may represent browsing or using a personal phone rather than cutting the security tether.",
            "investigative_action": "Cross-reference with forensic tool-mark analysis to verify if wire-cutter impressions match items found in suspect's possession."
        },
        {
            "dimension": "WITNESS_PERCEPTION_LIMITATION",
            "severity": "LOW",
            "observation_counterpoint": "Witness described clothing simply as 'black jacket', a common clothing item during winter evening hours.",
            "alternative_explanation": "Risk of confirmation bias conflating a casual shopper with the surveillance subject.",
            "investigative_action": "Perform formal photo lineup / detailed descriptive debriefing with witness."
        }
    ]

    prompt = (
        f"You are an adversarial forensic defense expert and reality reconstruction critic in a criminal theft case.\n"
        f"Hypothesis Under Challenge: {hypothesis_label}\n\n"
        f"Reconstructed Event Sequence:\n{sequence}\n\n"
        f"Layer 1 Deterministic Rule Violations Found:\n{layer1_issues}\n\n"
        f"Identified Spatiotemporal Gaps & Surveillance Blind Spots:\n{gaps}\n\n"
        f"TASK:\n"
        f"Generate 3 rigorous adversarial challenge notes identifying evidentiary gaps, lack of positive visual identification, "
        f"blind-spot ambiguity, and alternative innocent or accomplice explanations.\n\n"
        f"Return ONLY a JSON object with key 'challenges' containing a list of objects, each with keys:\n"
        f"- 'dimension': short uppercase string (e.g. 'BLIND_SPOT_AMBIGUITY', 'PHYSICAL_OCCLUSION', 'WITNESS_CONFIRMATION_BIAS')\n"
        f"- 'severity': 'CRITICAL', 'HIGH', or 'MEDIUM'\n"
        f"- 'observation_counterpoint': detailed critique of the evidence\n"
        f"- 'alternative_explanation': plausible alternative explanation consistent with the facts\n"
        f"- 'investigative_action': concrete step a detective must take to test or falsify this challenge"
    )

    system_instruction = (
        "You are an elite adversarial criminal defense forensic investigator. Your job is to find reasonable doubt, "
        "challenge assumptions in reconstructive evidence pipelines, and ensure innocent explanations are thoroughly examined."
    )

    try:
        res = await query_gemini_json(prompt=prompt, system_instruction=system_instruction, timeout=20.0)
        if res and isinstance(res, dict) and "challenges" in res and isinstance(res["challenges"], list):
            logger.info("Layer 2 Adversarial Self-Challenge generated by Live Gemini AI.")
            return res["challenges"]
    except Exception as e:
        logger.warning(f"Live Gemini Layer 2 call failed: {e}; using baseline fallback.")

    return fallback_notes
