"""
Evidence Reference Integrity Gate (RRE Core Security & Anti-Hallucination Policy)

Mandate:
Every meaningful statement, finding, claim, or hypothesis generated by RRE
must resolve through a strict provenance chain:
  Report statement -> Hypothesis / finding / observation -> Engine execution -> Evidence ID -> Current Case ID -> Original evidence artifact

If an unavailable evidence source is referenced as supporting fact/corroboration
(e.g., CCTV, POS, vehicle records when no such exhibits are attached to the current case),
the validator MUST reject the output with:
  UNSUPPORTED_EVIDENCE_REFERENCE
"""

import re
from typing import List, Dict, Any, Tuple, Set, Optional

class UnsupportedEvidenceReferenceException(Exception):
    """Raised when an engine, hypothesis, or report cites an unavailable evidence modality."""
    pass

class InvalidProvenanceReferenceException(Exception):
    """
    Raised when an engine, hypothesis, or report cites an engine execution record
    that does not exist or whose status is BLOCKED, FAILED, or has no usable output.
    """
    def __init__(self, error_data: Dict[str, Any]):
        self.error_data = error_data
        super().__init__(f"INVALID_PROVENANCE_REFERENCE: {error_data.get('reason')}")


# Forbidden modality patterns mapped to required evidence types
MODALITY_REQUIREMENTS: Dict[str, Set[str]] = {
    "VIDEO_CCTV": {"CCTV", "VIDEO", "MP4", "MOV", "AVI"},
    "FINANCIAL_POS": {"TRANSACTION_RECORD", "POS", "LEDGER", "INVENTORY", "CSV", "INVENTORY_RECORD"},
    "VEHICLE_TRACKING": {"VEHICLE_RECORD", "VEHICLE"}
}

# Regexes detecting positive factual claims of unavailable sources
# Note: Negative/gap statements like "CCTV is missing" or "No POS records" are permissible gap descriptions.
MODALITY_AFFIRMATIVE_REGEX: Dict[str, List[re.Pattern]] = {
    "VIDEO_CCTV": [
        re.compile(r'\b(cctv\s+(?:data|entry|footage|shows|confirms|timestamp|recording|camera))\b', re.IGNORECASE),
        re.compile(r'\b(camera\s+\d+\s+(?:timestamp|records|color|line\s+of\s+sight))\b', re.IGNORECASE),
        re.compile(r'\b(optical\s+tracking\s+sequence)\b', re.IGNORECASE),
        re.compile(r'\b(cctv_camera_\d+)\b', re.IGNORECASE),
        re.compile(r'\b(video\s+stream\s+parameters)\b', re.IGNORECASE)
    ],
    "FINANCIAL_POS": [
        re.compile(r'\b(pos\s+(?:transaction|audit|log|payment|record|match))\b', re.IGNORECASE),
        re.compile(r'\b(financial\s+inventory\s+ledger\s+audit)\b', re.IGNORECASE),
        re.compile(r'\b(sku-\d+)\b', re.IGNORECASE),
        re.compile(r'\b(point-of-sale\s+register)\b', re.IGNORECASE),
        re.compile(r'\bunexplained\s+deficit\s+of\s+\d+\s+units\b', re.IGNORECASE)
    ],
    "VEHICLE_TRACKING": [
        re.compile(r'\b(vehicle\s+exit\s+timestamp[s]?)\b', re.IGNORECASE),
        re.compile(r'\b(dark\s+sedan\s+depart(?:ing|ure))\b', re.IGNORECASE),
        re.compile(r'\b(vehicle\s+track(?:let)?|license\s+plate\s+candidate)\b', re.IGNORECASE),
        re.compile(r'\b(unregistered\s+dark\s+sedan)\b', re.IGNORECASE)
    ]
}

def get_available_modalities(case_evidence_list: List[Any]) -> Set[str]:
    """Inspects case exhibits and returns available modality keys."""
    types_in_case = set()
    for ev in case_evidence_list:
        ev_type = getattr(ev, "evidence_type", None)
        if ev_type:
            types_in_case.add(str(ev_type.value if hasattr(ev_type, "value") else ev_type).upper())

    available = set()
    for mod_name, allowed_types in MODALITY_REQUIREMENTS.items():
        if types_in_case.intersection(allowed_types):
            available.add(mod_name)
    return available

def validate_evidence_reference_integrity(
    case_evidence_list: List[Any],
    payload: Any,
    context_desc: str = "reconstruction"
) -> Tuple[bool, List[str]]:
    """
    Validates that the payload (hypothesis, finding, observation, report) does not
    assert positive factual findings from unavailable evidence modalities.

    Returns:
        (is_valid: bool, violations: List[str])
    """
    available_modalities = get_available_modalities(case_evidence_list)
    unavailable_modalities = set(MODALITY_REQUIREMENTS.keys()) - available_modalities

    violations: List[str] = []

    # Extract all text fragments to inspect
    text_corpus = _extract_text_corpus(payload)

    for text in text_corpus:
        # Ignore explicit negative gap statements (e.g., "No CCTV available", "Missing CCTV")
        if _is_explicit_negative_or_gap_statement(text):
            continue

        for unavail in unavailable_modalities:
            patterns = MODALITY_AFFIRMATIVE_REGEX.get(unavail, [])
            for pat in patterns:
                match = pat.search(text)
                if match:
                    violations.append(
                        f"UNSUPPORTED_EVIDENCE_REFERENCE: {context_desc} references unavailable modality '{unavail}' "
                        f"via claim '{match.group(0)}' in context: '{text[:120]}...'. "
                        f"No corresponding evidence exhibit is attached to the current case."
                    )

    if violations:
        return False, violations
    return True, []

def enforce_evidence_reference_integrity(
    case_evidence_list: List[Any],
    payload: Any,
    context_desc: str = "reconstruction"
):
    """
    Strict enforcement gate: raises UnsupportedEvidenceReferenceException if violated.
    Do not sanitize the sentence; reject the output completely.
    """
    is_valid, violations = validate_evidence_reference_integrity(
        case_evidence_list=case_evidence_list,
        payload=payload,
        context_desc=context_desc
    )
    if not is_valid:
        error_msg = " | ".join(violations)
        raise UnsupportedEvidenceReferenceException(error_msg)

def _extract_text_corpus(data: Any) -> List[str]:
    """Recursively flattens data structures to strings for inspection."""
    corpus = []
    if isinstance(data, str):
        corpus.append(data)
    elif isinstance(data, dict):
        for k, v in data.items():
            # Skip keys that are known to describe gaps or remediation
            if k in ["critical_gaps", "remediation", "missing_modalities", "failure_reason"]:
                continue
            corpus.extend(_extract_text_corpus(v))
    elif isinstance(data, (list, tuple, set)):
        for item in data:
            corpus.extend(_extract_text_corpus(item))
    elif hasattr(data, "__dict__"):
        corpus.extend(_extract_text_corpus(data.__dict__))
    return corpus

def _is_explicit_negative_or_gap_statement(text: str) -> bool:
    """Checks if text is merely noting the absence of evidence (permissible)."""
    text_lower = text.lower()
    negative_indicators = [
        "no cctv", "missing cctv", "cctv is missing", "without cctv", "cctv unavailable",
        "no video", "missing video", "without video",
        "no pos", "missing pos", "without pos", "zero transactions", "no sales recorded",
        "no vehicle", "missing vehicle", "without vehicle",
        "unmonitored", "unobserved", "not directly observed", "blind spot",
        "absence of", "fails to record", "lacks", "insufficient evidence"
    ]
    return any(ind in text_lower for ind in negative_indicators)


# ---------------------------------------------------------------------------
# Citation Provenance Integrity Validation (INVALID_PROVENANCE_REFERENCE)
# ---------------------------------------------------------------------------

ENGINE_CODE_PATTERN = re.compile(r'\b(E0[1-7]|I0[1-9]|I1[0-2]|F0[1-9]|FI0[1-7]|X0[1-6]|R0[1-4])\b')

def validate_provenance_citations(
    case_id: str,
    engine_id: str,
    citations: List[Any],
    execution_records: Dict[str, Any],
    report_id: Optional[str] = None,
    execution_id: Optional[str] = None,
    evidence_id: Optional[str] = None
) -> Tuple[bool, List[Dict[str, Any]]]:
    """
    Validates that every citation refers to an actual current-case engine execution
    record whose status is usable (SUCCESS or PARTIAL with outputs).
    
    If any citation references a BLOCKED, FAILED, or missing engine:
    Returns (False, [error_payloads]) adhering to the INVALID_PROVENANCE_REFERENCE standard.
    Never rewrites the claim; callers must reject it.
    """
    errors: List[Dict[str, Any]] = []

    for cit in citations:
        cit_text = cit if isinstance(cit, str) else str(cit.get("text", cit) if isinstance(cit, dict) else cit)
        referenced_eids = ENGINE_CODE_PATTERN.findall(cit_text)
        
        for ref_eid in referenced_eids:
            rec = execution_records.get(ref_eid)
            
            if rec is None:
                errors.append({
                    "error_code": "INVALID_PROVENANCE_REFERENCE",
                    "report_id": report_id,
                    "case_id": case_id,
                    "engine_id": engine_id,
                    "execution_id": execution_id or getattr(rec, "execution_id", None),
                    "evidence_id": evidence_id,
                    "citation_text": cit_text,
                    "referenced_engine_id": ref_eid,
                    "reason": f"Cites engine '{ref_eid}' which has no execution record in the current case."
                })
                continue
                
            rec_status = rec.status.value if hasattr(rec.status, "value") else str(rec.status)
            if rec_status == "BLOCKED":
                errors.append({
                    "error_code": "INVALID_PROVENANCE_REFERENCE",
                    "report_id": report_id,
                    "case_id": case_id,
                    "engine_id": engine_id,
                    "execution_id": execution_id or getattr(rec, "execution_id", None),
                    "evidence_id": evidence_id,
                    "citation_text": cit_text,
                    "referenced_engine_id": ref_eid,
                    "reason": f"Cites engine '{ref_eid}' whose execution status is BLOCKED (Failure reason: {getattr(rec, 'failure_reason', 'modality unavailable')}). Citations to BLOCKED engines are strictly invalid."
                })
            elif rec_status == "FAILED":
                errors.append({
                    "error_code": "INVALID_PROVENANCE_REFERENCE",
                    "report_id": report_id,
                    "case_id": case_id,
                    "engine_id": engine_id,
                    "execution_id": execution_id or getattr(rec, "execution_id", None),
                    "evidence_id": evidence_id,
                    "citation_text": cit_text,
                    "referenced_engine_id": ref_eid,
                    "reason": f"Cites engine '{ref_eid}' which FAILED during execution: {getattr(rec, 'failure_reason', 'execution error')}."
                })
            elif not getattr(rec, "outputs", None) or len(rec.outputs) == 0:
                errors.append({
                    "error_code": "INVALID_PROVENANCE_REFERENCE",
                    "report_id": report_id,
                    "case_id": case_id,
                    "engine_id": engine_id,
                    "execution_id": execution_id or getattr(rec, "execution_id", None),
                    "evidence_id": evidence_id,
                    "citation_text": cit_text,
                    "referenced_engine_id": ref_eid,
                    "reason": f"Cites engine '{ref_eid}' which has no usable outputs (NO_USABLE_OUTPUT)."
                })

    if errors:
        return False, errors
    return True, []

def enforce_provenance_reference_integrity(
    case_id: str,
    engine_id: str,
    citations: List[Any],
    execution_records: Dict[str, Any],
    report_id: Optional[str] = None
):
    """Raises InvalidProvenanceReferenceException if any citation is invalid."""
    is_valid, errors = validate_provenance_citations(
        case_id=case_id,
        engine_id=engine_id,
        citations=citations,
        execution_records=execution_records,
        report_id=report_id
    )
    if not is_valid:
        raise InvalidProvenanceReferenceException(errors[0])

