from enum import Enum

class Role(str, Enum):
    ADMIN = "ADMIN"
    LEAD_INVESTIGATOR = "LEAD_INVESTIGATOR"
    INVESTIGATOR = "INVESTIGATOR"
    FORENSIC_OFFICER = "FORENSIC_OFFICER"
    FINANCIAL_ANALYST = "FINANCIAL_ANALYST"
    PROSECUTOR_JUDGE = "PROSECUTOR_JUDGE"

class Department(str, Enum):
    INVESTIGATION = "INVESTIGATION"
    FORENSIC = "FORENSIC"
    FINANCIAL = "FINANCIAL"
    LEGAL = "LEGAL"
    ADMIN = "ADMIN"
    CORRELATED = "CORRELATED"

class CaseType(str, Enum):
    THEFT = "THEFT"

class CaseStatus(str, Enum):
    CREATED = "CREATED"
    EVIDENCE_COLLECTION = "EVIDENCE_COLLECTION"
    ANALYSIS = "ANALYSIS"
    RECONSTRUCTION = "RECONSTRUCTION"
    UNDER_REVIEW = "UNDER_REVIEW"
    CLOSED = "CLOSED"

class EvidenceType(str, Enum):
    CCTV = "CCTV"
    IMAGE = "IMAGE"
    AUDIO = "AUDIO"
    DOCUMENT = "DOCUMENT"
    TRANSACTION_RECORD = "TRANSACTION_RECORD"
    INVENTORY_RECORD = "INVENTORY_RECORD"
    VEHICLE_RECORD = "VEHICLE_RECORD"
    WITNESS_STATEMENT = "WITNESS_STATEMENT"
    FORENSIC_REPORT = "FORENSIC_REPORT"
    OTHER = "OTHER"

class ProcessingStatus(str, Enum):
    PENDING = "PENDING"
    ROUTING = "ROUTING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"

class ObservationType(str, Enum):
    PERSON_DETECTED = "PERSON_DETECTED"
    VEHICLE_DETECTED = "VEHICLE_DETECTED"
    OBJECT_DETECTED = "OBJECT_DETECTED"
    MOVEMENT_DETECTED = "MOVEMENT_DETECTED"
    TEXT_EXTRACTED = "TEXT_EXTRACTED"
    ENTITY_EXTRACTED = "ENTITY_EXTRACTED"
    TRANSACTION_FLAGGED = "TRANSACTION_FLAGGED"
    ENTRY_EVENT = "ENTRY_EVENT"
    EXIT_EVENT = "EXIT_EVENT"
    PHYSICAL_MARK_DETECTED = "PHYSICAL_MARK_DETECTED"
    AUDIO_TRANSCRIBED = "AUDIO_TRANSCRIBED"
    OTHER = "OTHER"

class TimeConfidence(str, Enum):
    EXACT = "EXACT"
    APPROXIMATE = "APPROXIMATE"
    ESTIMATED = "ESTIMATED"
    UNKNOWN = "UNKNOWN"

class TimeReliability(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    UNKNOWN = "UNKNOWN"

class EvidenceQuality(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    POOR = "POOR"

class VerificationStatus(str, Enum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    CORRECTED = "CORRECTED"
    REJECTED = "REJECTED"

class EntityType(str, Enum):
    PERSON = "PERSON"
    VEHICLE = "VEHICLE"
    ITEM = "ITEM"
    LOCATION = "LOCATION"
    DEVICE = "DEVICE"

class IdentityStatus(str, Enum):
    UNKNOWN = "UNKNOWN"
    CANDIDATE = "CANDIDATE"
    CONFIRMED = "CONFIRMED"
    EXCLUDED = "EXCLUDED"

class GeneratedBy(str, Enum):
    AI = "AI"
    HUMAN = "HUMAN"
    AI_HUMAN_REVISED = "AI_HUMAN_REVISED"

class ClaimStrength(str, Enum):
    STRONG = "STRONG"
    MODERATE = "MODERATE"
    WEAK = "WEAK"
    SPECULATIVE = "SPECULATIVE"

class EvidenceSupportLevel(str, Enum):
    STRONG = "STRONG"
    MODERATE = "MODERATE"
    LIMITED = "LIMITED"
    SPECULATIVE = "SPECULATIVE"

class HypothesisStatus(str, Enum):
    DRAFT = "DRAFT"
    CHALLENGED = "CHALLENGED"
    UNDER_REVIEW = "UNDER_REVIEW"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"

class GapConflictType(str, Enum):
    GAP = "GAP"
    HARD_CONTRADICTION = "HARD_CONTRADICTION"
    SOFT_DISCREPANCY = "SOFT_DISCREPANCY"
    SOURCE_DISAGREEMENT = "SOURCE_DISAGREEMENT"
    UNCERTAINTY = "UNCERTAINTY"

class Significance(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFORMATIONAL = "INFORMATIONAL"

class TargetType(str, Enum):
    OBSERVATION = "OBSERVATION"
    FINDING = "FINDING"
    CLAIM = "CLAIM"
    TIMELINE_EVENT = "TIMELINE_EVENT"
    HYPOTHESIS = "HYPOTHESIS"
    GAP_CONFLICT = "GAP_CONFLICT"
    ENTITY_LINK = "ENTITY_LINK"

class VerificationAction(str, Enum):
    ACCEPTED = "ACCEPTED"
    CORRECTED = "CORRECTED"
    REJECTED = "REJECTED"
